apiVersion: batch/v1
kind: Job
metadata:
  generateName: listfolder
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: presync
        image: docker-pullable://jocatalin/kubernetes-bootcamp@sha256:fb1a3ced00cecfc1f83f18ab5cd14199e30adc1b49aa4244f5d65ad3f5feb2a5
        command:
          - "ls"
          - "-al"
      restartPolicy: Never
  backoffLimit: 0