apiVersion: batch/v1
kind: Job
metadata:
  generateName: listfolder
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "ls"
          - "-al"
      restartPolicy: Never
  backoffLimit: 2