apiVersion: batch/v1
kind: Job
metadata:
  generateName: listfolder
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: presync
        image: jk82421/rails-migration-failed:v1
        command:
          - "sh"
          - "./bin/presync.sh"
      restartPolicy: Never
  backoffLimit: 0